### ISSUE TITLE
Considered to connect it to AI models like OpenGPT?

### ISSUE THREAD

**Issue by xetra11** [filiph/egamebook#154]
Hey I love you idea!
I am building a MMORPG project with Flutter and a friend shared your ebookgame engine game and the whole project's description. I had something similar in mind but actually tried it with AI models like OpenGPT.

Here is a small example of what I mean:
![image](https://user-images.githubusercontent.com/8149023/209180098-473ac589-cf37-4764-ab84-5fd03855bee4.png)

I guess that the whole concept might be very interesting when combined with an AI that can actually tell a story and determine things dynamically.

Looking forward to the engine and will definitely use it in my project if it is open sourced!

**Comment by filiph** [comment]
Nice! I was looking at this a few years ago. I purposefully stay away from ML model-based AI with this project because it's too unpredictable. ML models (like GPT-3) will happily lie if it makes their story "flow" better. (For example, after the combat with the soldier, try saying something like "buy a shirt from the soldier". It's possible that GPTchat will just let you do that.) In the case of egamebook, I wanted to have complete authorial control — if something's said in the generated story, it's true about the simulated world.

As ML models get more advanced, I think it's safe to assume that this issue will disappear. Plus, if I remember correctly, there are already some ways to keep the model truthful (or at least more truthful than it would be normally).

In any case, this is not an avenue I want to explore for this project at this point, but I welcome the idea!

**Comment by xetra11** [comment]
Good point. However I figured out that you can set boundaries if you just tell the AI so. So one might be able to state "only do stuff that fits the medieval era and a combat situation" then the AI _might_ not let you buy a shirt 🗡️
